from rspavel/centos_ompi:latest
# from proxyapps/proxy-ci-basecontainers:centos7

ARG APP
ARG DEPS
ARG INSECURE

# RUN yum update -y
# RUN yum install -y epel-release
# RUN yum install -y make cmake git mercurial graphviz gnupg2 R perl perl-devel
# RUN yum install -y patch bzip2*
# RUN yum install -y unzip
# RUN yum install -y perl-Data-Dumper
# RUN yum install -y perl-Thread-Queue
# RUN yum install -y centos-release-scl
# RUN yum --enablerepo=centos-sclo-rh-testing -y install devtoolset-7-gcc*

RUN useradd -m ci

COPY proxy-ci/ /home/ci/proxy-ci
COPY spack /home/ci/spack
RUN rm -rf /home/ci/.ccache
COPY ccache/ /home/ci/.ccache
USER root
RUN chown -R ci:ci /home/ci/proxy-ci /home/ci/.ccache /home/ci/spack
USER ci

WORKDIR /home/ci
RUN cp proxy-ci/centos7-packages.yaml spack/etc/spack/packages.yaml
ENV SPACK=/home/ci/spack/bin/spack
ENV SPACK_ROOT=/home/ci/spack

RUN scl enable devtoolset-7 '${SPACK} compiler find'

RUN ${SPACK} find
RUN if [ -n "${DEPS}" ]; then ${SPACK} install -j4 -v ${DEPS}; else ${SPACK} install -j4 -v --only dependencies ${APP}; fi
RUN ${SPACK} -d  ${INSECURE} install --source -j4 --only package -v ${APP}
